### ISSUE TITLE
Cannot trade taxed tokens

### ISSUE THREAD

**Issue by WilliamWelsh** [Cryptorubic/rubic-sdk#125]
When using `2.4.3`, anytime a taxed token is attempted to trade, it throws an execution reverted error. Thoughts?

![telegram-cloud-photo-size-1-5082587740750588500-x](https://user-images.githubusercontent.com/16886888/179337691-39ceaa5e-89d0-4f11-9504-b2c3b54e601c.jpg)

**Comment by BigBallHead** [comment]
Hello ! What pair did you use for the swap and what was the amount?
